apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: clustercode
        image: quay.io/ccremer/clustercode:master
        args:
        - operate
        - --operator.clustercode-image=quay.io/ccremer/clustercode:master
        - --operator.ffmpeg-image=docker.io/jrottenberg/ffmpeg:4.1-alpine
