== Media Extensions

When scanning, clustercode will look for files that end with these extensions.
Only the file name matters, not what is in the files.
If the files are not video files, `+ffmpeg+` will likely fail.
Do not provide a leading dot `+.+` before the extensions in the setting.
Only the last part after the last dot in the file will count as extension.

== Skip Media

When a clustercode node has converted a video, all other nodes (including itself) need to know which media have already been processed.
One way to ensure that the same media will not get picked again is to create an empty file that matches exactly the original file name and add a special extension.
If clustercode detects a video file, but there is another file with the same name but with this skip extension, it won't get in the list of possible processing candidates.
This is why clustercode needs write permissions on the input directories.
No other files will be touched, deleted or otherwise modified.

== Profiles

`+ffmpeg+` needs some parameters to know how to convert the input files.
These parameters are stored in profiles.
If you want to create custom ones, copy from the included profiles and start modifying from them.

== Media Scan Interval

This is the interval in minutes if no suitable media could be found before and after encoding.
If a new video has been added in the meantime, it will be picked up at the next scan.

== Profile match strategies

The setting accepts certain space-separated strings of pre-defined entries.
The order in which they are specified *does* matter.
The search for profiles will stop as soon as one is found in the matcher.
So if you specify `+COMPANION DEFAULT DIRECTORY_STRUCTURE+` The profile scanner will never look in the subdirectories of `+/profiles+` if the default profile exists.

=== Companion

This strategy searches for a file named exactly as the media file, but with an additional extension.
Using this strategy you can override any profile in the `+CC_PROFILE_DIR+` directory.

[example]
====
* Media file: `+/input/0/movies/ratavA.mkv+`
* Profile file: `+/input/0/movies/ratavA.mkv.ffmpeg+`
====

will match before there is a `+/profiles/0/profile.ffmpeg+`.

=== Directory Structure

Provides a matcher that will look recursively in the directory structure until it finds the first matching profile.

[example]
====
* Media file: `+/input/0/movies/action/ratavA.mkv+`
* Profile file: `+/profiles/0/movies/profile.ffmpeg+`
* Try #1: `+/profiles/0/movies/action/profile.ffmpeg+` -> not found
* Try #2: `+/profiles/0/movies/profile.ffmpeg+` -> found
* `+/profiles/0/profile.ffmpeg+` will not be checked
====

=== Default

Provides a matcher that will look for a file named `+CC_PROFILE_DIR/CC_PROFILE_FILE_DEFAULT.CC_PROFILE_FILE_EXTENSION+`.
It should be a last-resort matcher that catches all unmatched media files.
