apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  template:
    spec:
      containers:
        - name: clustercode
          image: $E2E_IMAGE
          args:
            - -v
            - operate
            - --operator.clustercode-image
            - $E2E_IMAGE
            - --scan.role-name=clustercode-editor-role
