name: Build

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - charts/**
      - docs/**

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run build
        run: make build-docker

  vite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Run build
        run: make build-ui
