name: E2E

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - docs/**

jobs:
  kuttl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: make test-e2e

      - name: Cleanup
        run: make clean
        if: always()
