name: Lint

on:
  pull_request: {}

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run linters
        run: make lint-go git-diff

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          args: --timeout 5m --out-${NO_FUTURE}format colored-line-number

  ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Run linters
        run: make lint-ui git-diff
