name: Test

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - charts/**
      - docs/**

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: make test-integration

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
          cache-dependency-path: ui/package-lock.json

      - name: Run tests
        uses: cypress-io/github-action@v4
        with:
          component: true
          working-directory: ui

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: e2e-videos
          path: ui/cypress/videos
